# Generated by Django 3.0.8 on 2020-07-17 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='djangoClasses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=60)),
                ('Course_Number', models.IntegerField(blank=True, default=None)),
                ('Instructor_Name', models.CharField(blank=True, max_length=100)),
                ('Duration', models.FloatField(blank=True, default=None)),
            ],
        ),
    ]
