# Generated by Django 3.0.8 on 2020-07-17 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangoclasses',
            name='Duration',
            field=models.CharField(blank=True, default=None, max_length=60),
        ),
    ]
